name: End-to-end tests

permissions:
  contents: write
  pages: write
  id-token: write

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [electron, chrome]

    env:
      CYPRESS_username: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    steps:
      - name: Checkout Cypress Framework
        uses: actions/checkout@v4

      - name: Clone Toolshop
        run: |
          git clone https://github.com/automationcamp/automationcamp-toolshop.git

      - name: Start Toolshop
        run: |
          cd automationcamp-toolshop
          npm run setup
          npm start &

      - name: Wait for Toolshop
        run: npx wait-on http://localhost:5173 --timeout 120000

      - name: Check Toolshop
        run: curl http://localhost:5173

      - name: Cypress run on ${{ matrix.browser }}
        uses: cypress-io/github-action@v7
        with:
          browser: ${{ matrix.browser }}
          record: true
        env:
          CYPRESS_BROWSER: ${{ matrix.browser }}

      - name: Upload Reports as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports-${{ matrix.browser }}
          path: cypress/reports